### ISSUE TITLE
Update-sites (release/snapshot) are down

### ISSUE THREAD

**Issue by mwerlitz** [mapstruct/mapstruct-eclipse#47] opened 2021-05-27 09:57 UTC
The release (https://dl.bintray.com/mapstruct/mapstruct-eclipse-site/) and snapshot update-site seem to be down at the moment.

**Comment by filiphr** [comment] 2021-05-27 17:47
This is a duplicate of #46 we have published the plugin to a new location (https://mapstruct.org/eclipse/). The plugin (https://marketplace.eclipse.org/content/mapstruct-eclipse-plugin) is also updated in the Eclipse marketplace. Can you please tell us where you found this links?

**Closed as completed by filiphr** 2021-05-27 17:47 UTC

**Comment by mwerlitz** [comment] 2021-05-31 09:07
I used the links in README.md, which is fixed now.
